jobs:
- job: Test
  displayName: 'Test'
  variables:
    TEST_HARNESS: "true"
    TRAVIS_OS_NAME: "linux"
    TRAVIS: "true"
    TRAVIS_PULL_REQUEST: $(System.PullRequest.PullRequestNumber)
    TRAVIS_PULL_REQUEST_SHA: $(Build.SourceVersion)
    COMPILER: Android 
    GRAPHICS: OpenGLES2 
    PLATFORM: SDL MODE=Compile 
    ANDROID_API_LEVEL: 29 
    ANDROID_BUILD_TOOLS_VERSION: 29.0.3
  pool:
    vmImage: 'ubuntu-20.04'

  steps:
    - checkout: self
      persistCredentials: true
      
    - script: |
        echo "y" | $ANDROID_HOME/tools/bin/sdkmanager --channel=1 --install "tools" "platform-tools" "extras;google;google_play_services" "extras;google;m2repository" "extras;android;m2repository" "build-tools;29.0.3" "platforms;android-29" "ndk;22.0.6917172"
        git clone https://github.com/enigma-dev/enigma-dev.git
        cd enigma-dev
        ./CI/install_emake_deps.sh
        git clone --depth 1 https://github.com/enigma-dev/enigma-android.git android
        make -j4 && CLI_ENABLE_EGM=FALSE make -j4 emake
        ./ci-build.sh
